### ISSUE TITLE
() Wintergrasp battle: NPC Elites respawn when Wintergrasp battle ends, which they should not!

### ISSUE THREAD

**Issue by YggdrasilWotLK** [YggdrasilWotLK/Yggdrasil-WoW#166]
Wintergrasp battle: NPC Elites respawn when Wintergrasp battle ends, which they should not!

**Comment by YggdrasilWotLK** [comment]
https://github.com/azerothcore/azerothcore-wotlk/blob/dd96b57be4c7178fbf376bdd7523aa801512ecda/src/server/game/Battlefield/Zones/BattlefieldWG.cpp#L146C1-L155C72 the logic here needs to be improved to have state tracking (edit: this only regards WG's boot state)

**Comment by YggdrasilWotLK** [comment]
Player-provided context: 

![Image](https://github.com/user-attachments/assets/369d405b-a099-4651-bb95-805343942041)

After the side already holding WG wins, loser's dead NPCs respawn

![Image](https://github.com/user-attachments/assets/f7ef1602-fb17-44fd-b7ce-052d24a41cbf)

**Comment by YggdrasilWotLK** [comment]
See also https://github.com/azerothcore/azerothcore-wotlk/blob/dd96b57be4c7178fbf376bdd7523aa801512ecda/src/server/game/Battlefield/Zones/BattlefieldWG.h#L1334-L1357

Which calls `m_WG->ShowNpc(creature, true);` on the NPCs to show, prompting an immediate respawn through https://github.com/azerothcore/azerothcore-wotlk/blob/dd96b57be4c7178fbf376bdd7523aa801512ecda/src/server/game/Battlefield/Battlefield.cpp#L509C1-L524C1

`    if (!creature->IsAlive())
        creature->Respawn(true);`

**Comment by YggdrasilWotLK** [comment]
https://github.com/YggdrasilWotLK/yggdrasilcore/commit/5671a93cf183b955a797e5df1b05a250816f16d6 should fix it, @Ye-Old-Potato could you give this a test please? QA should be ready in about 30 minutes from now

**Comment by YggdrasilWotLK** [comment]
Fix verified by tester, pushed live to prod now

**Comment by YggdrasilWotLK** [comment]
Reopening as player reports this issue may not be resolved yet

**Comment by Alexander990608** [comment]
Hello there! Since i have tested it up and sadly it is not fixed.

I am talking about Elite NPC's which i will write their names one by one.


Alliance NPC Elites:
1. Anchorite Tessa
2. Bowyer Randolph
3. Commander Zanneth
4. Senior Demolitionist Legoso
5. Siege Master Stouthandle
6. Sorceress Kaylana
7. Tactical Officer Ahbramis


Horde NPC Elites:
1. Commander Dardosh
2. Hoodoo Master Fu'jin
3. Lieutenant Murp
4. Primalist Mulfort
5. Siegesmith Stronghoof
6. Tactical Officer Kilrath
7. Vieron Blazefeather

When you go Wintergrasp, start the battle, then go to Fortress and kill an Elite NPC that i have told you (depends which faction controls it, or you can go to Alliance or Horde Landing zone, then end the battle, you will see that NPC it will respawn after Wintergrasp ends, which it should not respawn. You have also Screenshots up there.

**Comment by YggdrasilWotLK** [comment]
@Ye-Old-Potato could you please confirm which NPCs you tested with?

**Comment by Alexander990608** [comment]
Second Screenshots, this time on Alliance NPC Elites:

https://i.postimg.cc/sx5Tzh9p/1.webp
https://i.postimg.cc/Jzz56gg3/2.webp

**Comment by YggdrasilWotLK** [comment]
Thanks, found a potential cause for the continued issue. Will test within the next few days!

**Comment by YggdrasilWotLK** [comment]
All set and live now! https://github.com/YggdrasilWotLK/yggdrasilcore/commit/dfd5659aa89dc2360b8afd58714a7cf6c3b9a2fa
